// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF_HjTVXDRatmiSzcgAMIgNkSIBRFcfMQ',
    appId: '1:827408901014:web:4e8f80617e2191be2d33b7',
    messagingSenderId: '827408901014',
    projectId: 'mobilemech-e623a',
    authDomain: 'mobilemech-e623a.firebaseapp.com',
    storageBucket: 'mobilemech-e623a.firebasestorage.app',
    measurementId: 'G-EWFS010G8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7S_smgrKNOLpYoWkW0GL5EHVujmtbBMY',
    appId: '1:827408901014:android:b2a6a78c9f8c9e412d33b7',
    messagingSenderId: '827408901014',
    projectId: 'mobilemech-e623a',
    storageBucket: 'mobilemech-e623a.firebasestorage.app',
  );
}
